spring.application.name=hw23school
spring.datasource.url=jdbc:postgresql://localhost:1234/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

path.to.avatars.folder=C:\Users\nikit\YandexDisk\Coding\prac_java\hw23school\avatars
